package com.practical_plushies_mobs.registry;

import com.practical_plushies_mobs.PracticalPlushiesMobs;
import com.practical_plushies_mobs.plushies.variants.BigPlushie;
import com.practical_plushies_mobs.plushies.variants.FloorPlushie;
import com.practical_plushies_mobs.plushies.variants.HugePlushie;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

import java.util.ArrayList;

public class PlushieRegistry {
    private static final FabricBlockSettings DEFAULT_PLUSHIE_SETTINGS = FabricBlockSettings.create().strength(0.5f).nonOpaque().sounds(BlockSoundGroup.WOOL);
    public static final Block ASAKI_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block BLAZE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block BREEZE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CAVE_SPIDER_PLISHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CANDYCAKE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CREEPER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block DROWNED_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ELDER_GUARDIAN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ENDERDRAGON_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ENDERMAN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block EVOKER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block GHAST_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block GUARDIAN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block HUSK_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block MAGMA_CUBE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PETER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PIGLIN_BRUTE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PIGLIN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PILLAGER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PHANTOM_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block RAVANGER_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SHULKER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SLIME_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SKELETON_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SPIDER_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block STRAY_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block VEX_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block VINDICATOR_PLUSHIE =new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WARDEN_PLUSHIE =new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WITCH_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WITHER_SKELETON_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WITHER_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block YECHEYYY_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ZOGLIN_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ZOMBIE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SKELETON_HORSE_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ZOMBIE_VILLAGER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ZOMBIFIED_PIGLIN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ARMADILLO_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block BAT_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block DONKEY_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block GLOW_SQUID_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block GOAT_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block IRON_GOLEM_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block LLAMA_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block MULE_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block POLAR_BEAR_PLUSHIE = new FloorPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PUFFERFISH_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SQUID_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block STRIDER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block TRADER_LAMA_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block VILLAGER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WANDERING_TRADER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block ALLAY_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block AXOLOTL_PLUSHIE = new HugePlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block BEE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CHICKEN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block COW_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block FOX_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PARROT_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PIG_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SHEEP_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block TURTLE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CAMEL_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block HORSE_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block MOOSHROOM_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block FROG_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block RABBIT_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block CAT_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block WOLF_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block SNIFFER_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block DOLPHIN_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final Block PANDA_PLUSHIE = new BigPlushie(DEFAULT_PLUSHIE_SETTINGS);
    public static final ArrayList<Block> PLUSHIES = new ArrayList<>();

    public static void register() {
        registerPlushie(ASAKI_PLUSHIE, "asaki_plushie");
        registerPlushie(BLAZE_PLUSHIE, "blaze_plushie");
        registerPlushie(BREEZE_PLUSHIE, "breeze_plushie");
        registerPlushie(CAVE_SPIDER_PLISHIE, "cave_spider_plushie");
        registerPlushie(CANDYCAKE_PLUSHIE, "candycake_plushie");
        registerPlushie(DROWNED_PLUSHIE, "drowned_plushie");
        registerPlushie(ELDER_GUARDIAN_PLUSHIE, "elder_guardian_plushie");
        registerPlushie(CREEPER_PLUSHIE, "creeper_plushie");
        registerPlushie(ENDERDRAGON_PLUSHIE, "enderdragon_plushie");
        registerPlushie(ENDERMAN_PLUSHIE, "enderman_plushie");
        registerPlushie(EVOKER_PLUSHIE, "evoker_plushie");
        registerPlushie(GHAST_PLUSHIE, "ghast_plushie");
        registerPlushie(GUARDIAN_PLUSHIE, "guardian_plushie");
        registerPlushie(HUSK_PLUSHIE, "husk_plushie");
        registerPlushie(MAGMA_CUBE_PLUSHIE, "magma_cube_plushie");
        registerPlushie(PETER_PLUSHIE, "peter_plushie");
        registerPlushie(PIGLIN_BRUTE_PLUSHIE, "piglin_brute_plushie");
        registerPlushie(PIGLIN_PLUSHIE, "piglin_plushie");
        registerPlushie(PILLAGER_PLUSHIE, "pillager_plushie");
        registerPlushie(PHANTOM_PLUSHIE, "phantom_plushie");
        registerPlushie(RAVANGER_PLUSHIE, "ravanger_plushie");
        registerPlushie(SHULKER_PLUSHIE, "shulker_plushie");
        registerPlushie(SLIME_PLUSHIE, "slime_plushie");
        registerPlushie(SKELETON_PLUSHIE, "skeleton_plushie");
        registerPlushie(SPIDER_PLUSHIE, "spider_plushie");
        registerPlushie(STRAY_PLUSHIE, "stray_plushie");
        registerPlushie(VEX_PLUSHIE, "vex_plushie");
        registerPlushie(VINDICATOR_PLUSHIE, "vindicator_plushie");
        registerPlushie(WARDEN_PLUSHIE, "warden_plushie");
        registerPlushie(WITCH_PLUSHIE, "witch_plushie");
        registerPlushie(WITHER_SKELETON_PLUSHIE, "wither_skeleton_plushie");
        registerPlushie(WITHER_PLUSHIE, "wither_plushie");
        registerPlushie(YECHEYYY_PLUSHIE, "yecheyyy_plushie");
        registerPlushie(ZOGLIN_PLUSHIE, "zoglin_plushie");
        registerPlushie(ZOMBIE_PLUSHIE, "zombie_plushie");
        registerPlushie(SKELETON_HORSE_PLUSHIE, "skeleton_horse_plushie");
        registerPlushie(ZOMBIE_VILLAGER_PLUSHIE, "zombie_villager_plushie");
        registerPlushie(ZOMBIFIED_PIGLIN_PLUSHIE, "zombified_piglin_plushie");
        registerPlushie(ARMADILLO_PLUSHIE, "armadillo_plushie");
        registerPlushie(BAT_PLUSHIE, "bat_plushie");
        registerPlushie(DONKEY_PLUSHIE, "donkey_plushie");
        registerPlushie(GLOW_SQUID_PLUSHIE, "glow_squid_plushie");
        registerPlushie(GOAT_PLUSHIE, "goat_plushie");
        registerPlushie(IRON_GOLEM_PLUSHIE, "iron_golem_plushie");
        registerPlushie(LLAMA_PLUSHIE, "llama_plushie");
        registerPlushie(MULE_PLUSHIE, "mule_plushie");
        registerPlushie(POLAR_BEAR_PLUSHIE, "polar_bear_plushie");
        registerPlushie(PUFFERFISH_PLUSHIE, "pufferfish_plushie");
        registerPlushie(SQUID_PLUSHIE, "squid_plushie");
        registerPlushie(STRIDER_PLUSHIE, "strider_plushie");
        registerPlushie(TRADER_LAMA_PLUSHIE, "trader_lama_plushie");
        registerPlushie(VILLAGER_PLUSHIE, "villager_plushie");
        registerPlushie(WANDERING_TRADER_PLUSHIE, "wandering_trader_plushie");
        registerPlushie(ALLAY_PLUSHIE, "allay_plushie");
        registerPlushie(AXOLOTL_PLUSHIE, "axolotl_plushie");
        registerPlushie(BEE_PLUSHIE, "bee_plushie");
        registerPlushie(CHICKEN_PLUSHIE, "chicken_plushie");
        registerPlushie(COW_PLUSHIE, "cow_plushie");
        registerPlushie(FOX_PLUSHIE, "fox_plushie");
        registerPlushie(PARROT_PLUSHIE, "parrot_plushie");
        registerPlushie(PIG_PLUSHIE, "pig_plushie");
        registerPlushie(SHEEP_PLUSHIE, "sheep_plushie");
        registerPlushie(TURTLE_PLUSHIE, "turtle_plushie");
        registerPlushie(CAMEL_PLUSHIE, "camel_plushie");
        registerPlushie(HORSE_PLUSHIE, "horse_plushie");
        registerPlushie(MOOSHROOM_PLUSHIE, "mooshroom_plushie");
        registerPlushie(FROG_PLUSHIE, "frog_plushie");
        registerPlushie(RABBIT_PLUSHIE, "rabbit_plushie");
        registerPlushie(CAT_PLUSHIE, "cat_plushie");
        registerPlushie(WOLF_PLUSHIE, "wolf_plushie");
        registerPlushie(SNIFFER_PLUSHIE, "sniffer_plushie");
        registerPlushie(DOLPHIN_PLUSHIE, "dolphin_plushie");
        registerPlushie(PANDA_PLUSHIE, "panda_plushie");
        PlushieItemGroupRegistry.addItemGroupEntries(PLUSHIES);
    }

    private static void registerPlushie(Block plushieInstance, String identifier) {
        Registry.register(Registries.BLOCK, new Identifier(PracticalPlushiesMobs.MODID, identifier), plushieInstance);
        Registry.register(Registries.ITEM, new Identifier(PracticalPlushiesMobs.MODID, identifier), new BlockItem(plushieInstance, new FabricItemSettings()));
        PLUSHIES.add(plushieInstance);
    }
}
